### ISSUE TITLE
Lots of issues with Mage2

### ISSUE THREAD

**Issue by igc-ruud** [magenx/Magento-Automated-Server-Configuration-from-MagenX#35]
I just installed the first Mage2 server and there are a lot of issues:

Issue 1 - Phpmyadmin is not loaded:
http://www.mage2dev.nl/0B7B8ihpE6Co_PMA

Issue 2 - Opcache Gui won't load:
http://www.mage2dev.nl/lCBaQHYTwbXR_opcache_gui.php

Issue 3 - Admin gives a lot of jquery errors:
jquery.js:9666 GET http://www.mage2dev.nl/admin_16wn4h/mui/index/render/key/0c3c5da319ded3c6ab…t%5D=1&sorting%5Bfield%5D=entity_id&sorting%5Bdirection%5D=asc&isAjax=true 500 (Internal Server Error)

**Comment by igc-ruud** [comment]
in our case it was a wrong nginx configuration.

Change:
location / {
try_files $uri $uri/ /index.php;
}

To

location / {
try_files $uri $uri/ /index.php?$args;
}

Hope it helps!

Only now the phpmyadmin and opcache gui are not working

**Comment by magenx** [comment]
yes, "args" was changed recently, just to test.
but other locations and php files are denied by default, you need to define them in php{} block.

**Comment by igc-ruud** [comment]
But the mage1 script automatically allows those scripts to run

**Comment by magenx** [comment]
magento 2 config just a bit different

**Comment by uinique-ruud** [comment]
On the mage2 hosting I resolved the origin of the issue. Not from the logs, but with trial and error.

What I noticed is that when multiple users are logged in to the admin, and 1 is changing for example the order of the categories. When another user tries to access the manage categories page, he gets the error shown above.

When I enabled the indexer to run on schedule the issue was not happening anymore.

For magento 1 I have no clue yet and nothing is displayed in any logs.
